fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 'v1.0.0'
    wget:
      repo: "https://github.com/maestrodev/puppet-wget"
      ref: 'v1.7.3'
  symlinks:
    leiningen: "#{source_dir}"
